apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -medium-wss

resources:
- ../base

commonLabels:
  app: pmbench-normal-medium-wss

configMapGenerator:
- name: pmbench-normal
  behavior: merge
  literals:
    - extra='--pattern normal --shape 1280000 --setsize 40000 --mapsize 40000 2000000 --initialize -a touch -j 4'

  # for 40GB wss, you should use --shape 1280000
  # 1sigma(68%) offset= 5000MiB 1280000pages   accessed memory=10000MiB  2560000pages
  # 2sigma(95%) offset=10000MiB 2560000pages   accessed memory=20000MiB  5120000pages
  # 3sigma(99%) offset=20000MiB 5120000pages   accessed memory=40000MiB 10240000pages

patches:
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: foo
    kind: foo
    metadata:
      name: foo
    spec:
      template:
        spec:
          containers:
          - name: generator
            resources:
              requests:
                cpu: 8
                memory: 45G
              limits:
                cpu: 8
                memory: 45G
