apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -medium-wss

bases:
- ../base

commonLabels:
  app: redis-memtier-medium-wss

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - keymaximum_gen=500000
    - keymaximum_load=500000
    - extra='--key-stddev=500000'

patches:
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: foo
    kind: foo
    metadata:
      name: foo
    spec:
      template:
        spec:
          containers:
          - name: service
            resources:
              requests:
                cpu: 2
                memory: 38G
              limits:
                cpu: 2
                memory: 38G
          - name: generator
            resources:
              requests:
                cpu: 2
                memory: 2G
              limits:
                cpu: 2
                memory: 2G
