apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -medium-wss

bases:
- ../base

commonLabels:
  app: redis-memtier-medium-wss

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - keymaximum_gen=500000
    - keymaximum_load=500000
    - extra='--key-stddev=500000'

patchesStrategicMerge:
  - resources.yaml
