apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-memtier
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              cpu: 2
              memory: 38G
            limits:
              cpu: 2
              memory: 38G
        - name: memtier
          resources:
            requests:
              cpu: 2
              memory: 2G
            limits:
              cpu: 2
              memory: 2G
