apiVersion: v1
kind: Namespace
metadata:
  name: fluentd
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: wca
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-state-metrics
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: cadvisor