apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluentd
configMapGenerator:
  - name: fconf
    files:
    - configurations/fluent.conf
    - configurations/memtier.conf
    - configurations/mutilate.conf
    - configurations/specjbb.conf
    - configurations/stress.conf
    - configurations/sysbench.conf

resources:
  - daemonset.yaml
  - service.yaml
  - service_account.yaml
  - service_monitor.yaml
