apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -small

bases:
- ../base

commonLabels:
  app: redis-memtier-small

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - keymaximum_gen=250000
    - keymaximum_load=250000
    - extra='--key-stddev=12500'

patchesStrategicMerge:
  - resources.yaml
