apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: specjbb
spec:
  template:
    spec:
      containers:
      # Minimal resource for specjbb.controller.preset.ir=1000
        - name: backend
          resources:
            requests:
              cpu: 2
              memory: 6G
            limits:
              cpu: 2
              memory: 6G
        - name: injector
          resources:
            requests:
              cpu: 1
              memory: 3G
            limits:
              cpu: 1
              memory: 3G
        - name: controller
          resources:
            requests:
              cpu: 1
              memory: 3G
            limits:
              cpu: 1
              memory: 3G
