nameSuffix: -medium

bases:
- ../base

commonLabels:
  app: sysbench-memory-medium
  size: medium

patchesStrategicMerge:
  - resources.yaml

configMapGenerator:
- name: sysbench-memory
  behavior: merge
  literals:
    - threads=1
    - memory=4g
    - report_interval=1
