# Copyright (c) 2020 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import re
from unittest.mock import patch

from tests.testing import create_open_mock, relative_module_path
from wca.metrics import MetricName
from wca.zoneinfo import get_zoneinfo_measurements, DEFAULT_REGEXP


@patch('builtins.open', new=create_open_mock({
    "/proc/zoneinfo": open(relative_module_path(__file__, 'fixtures/proc-zoneinfo.txt')).read(),
}))
def test_parse_proc_zoneinfo(*mocks):
    assert get_zoneinfo_measurements(re.compile(DEFAULT_REGEXP)) == {
        MetricName.PLATFORM_ZONEINFO: {'0': {'high': 99030.0,
                                             'hmem_autonuma_promote_dst': 2151.0,
                                             'hmem_autonuma_promote_src': 0.0,
                                             'hmem_reclaim_demote_dst': 0.0,
                                             'hmem_reclaim_demote_src': 0.0,
                                             'hmem_reclaim_promote_dst': 0.0,
                                             'hmem_reclaim_promote_src': 0.0,
                                             'hmem_swapcache_promote_dst': 0.0,
                                             'hmem_swapcache_promote_src': 0.0,
                                             'hmem_unknown': 0.0,
                                             'low': 50272.0,
                                             'managed': 48758776.0,
                                             'min': 1514.0,
                                             'nr_bounce': 0.0,
                                             'nr_free_cma': 0.0,
                                             'nr_free_pages': 44816301.0,
                                             'nr_kernel_stack': 11896.0,
                                             'nr_mlock': 0.0,
                                             'nr_page_table_pages': 67830.0,
                                             'nr_zone_active_anon': 103024.0,
                                             'nr_zone_active_file': 69737.0,
                                             'nr_zone_inactive_anon': 2071.0,
                                             'nr_zone_inactive_file': 51401.0,
                                             'nr_zone_unevictable': 0.0,
                                             'nr_zone_write_pending': 27.0,
                                             'nr_zspages': 0.0,
                                             'numa_foreign': 0.0,
                                             'numa_hit': 27514862304.0,
                                             'numa_interleave': 36755.0,
                                             'numa_local': 27514857506.0,
                                             'numa_miss': 1532135.0,
                                             'numa_other': 1536941.0,
                                             'present': 49542144.0,
                                             'spanned': 49545216.0},
                                       '1': {'high': 100606.0,
                                             'hmem_autonuma_promote_dst': 120221148.0,
                                             'hmem_autonuma_promote_src': 0.0,
                                             'hmem_reclaim_demote_dst': 0.0,
                                             'hmem_reclaim_demote_src': 122231089.0,
                                             'hmem_reclaim_promote_dst': 149.0,
                                             'hmem_reclaim_promote_src': 0.0,
                                             'hmem_swapcache_promote_dst': 0.0,
                                             'hmem_swapcache_promote_src': 0.0,
                                             'hmem_unknown': 0.0,
                                             'low': 51072.0,
                                             'managed': 49534996.0,
                                             'min': 1538.0,
                                             'nr_accessed': 595514.0,
                                             'nr_active_anon': 44764263.0,
                                             'nr_active_file': 84.0,
                                             'nr_anon_pages': 45864007.0,
                                             'nr_anon_transparent_hugepages': 0.0,
                                             'nr_bounce': 0.0,
                                             'nr_dirtied': 7849.0,
                                             'nr_dirty': 6.0,
                                             'nr_file_hugepages': 0.0,
                                             'nr_file_pages': 66.0,
                                             'nr_file_pmdmapped': 0.0,
                                             'nr_free_cma': 0.0,
                                             'nr_free_pages': 99683.0,
                                             'nr_inactive_anon': 1099415.0,
                                             'nr_inactive_file': 52.0,
                                             'nr_isolated_anon': 0.0,
                                             'nr_isolated_file': 0.0,
                                             'nr_kernel_misc_reclaimable': 0.0,
                                             'nr_kernel_stack': 9256.0,
                                             'nr_mapped': 34.0,
                                             'nr_mlock': 0.0,
                                             'nr_page_table_pages': 90638.0,
                                             'nr_promote_fail': 0.0,
                                             'nr_promote_isolate_fail': 0.0,
                                             'nr_promote_ratelimit': 0.0,
                                             'nr_promoted': 0.0,
                                             'nr_shmem': 4.0,
                                             'nr_shmem_hugepages': 0.0,
                                             'nr_shmem_pmdmapped': 0.0,
                                             'nr_slab_reclaimable': 15083.0,
                                             'nr_slab_unreclaimable': 46869.0,
                                             'nr_unevictable': 0.0,
                                             'nr_unstable': 0.0,
                                             'nr_vmscan_immediate_reclaim': 0.0,
                                             'nr_vmscan_write': 0.0,
                                             'nr_writeback': 0.0,
                                             'nr_writeback_temp': 0.0,
                                             'nr_written': 7780.0,
                                             'nr_zone_active_anon': 44764263.0,
                                             'nr_zone_active_file': 84.0,
                                             'nr_zone_inactive_anon': 1099415.0,
                                             'nr_zone_inactive_file': 52.0,
                                             'nr_zone_unevictable': 0.0,
                                             'nr_zone_write_pending': 6.0,
                                             'nr_zspages': 0.0,
                                             'numa_foreign': 66862806.0,
                                             'numa_hit': 4253130819.0,
                                             'numa_interleave': 36586.0,
                                             'numa_local': 4253071940.0,
                                             'numa_miss': 0.0,
                                             'numa_other': 58879.0,
                                             'numa_try_migrate': 6101781.0,
                                             'present': 50331648.0,
                                             'spanned': 50331648.0,
                                             'workingset_activate': 0.0,
                                             'workingset_nodereclaim': 0.0,
                                             'workingset_nodes': 0.0,
                                             'workingset_refault': 0.0,
                                             'workingset_restore': 0.0},
                                       '2': {'high': 0.0,
                                             'low': 0.0,
                                             'managed': 0.0,
                                             'min': 0.0,
                                             'present': 0.0,
                                             'spanned': 0.0},
                                       '3': {'high': 0.0,
                                             'low': 0.0,
                                             'managed': 0.0,
                                             'min': 0.0,
                                             'present': 0.0,
                                             'spanned': 0.0}}}
