apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pmbench
spec:
  template:
    spec:
      containers:
        - name: pmbench
          resources:
            requests:
              cpu: 4
              memory: 4G
