# Full example for Mesos with anomalies stored in Kafka.

runner: !DetectionRunner
  node: !MesosNode
    mesos_agent_endpoint: 'http://127.0.0.1:5051'
    timeout: 5
    ssl: !SSL
      server_verify: True
      client_cert_path: "$PATH/apiserver-aurora-client.crt"
      client_key_path: "$PATH/apiserver-aurora-client.key"

  action_delay: 1.

  metrics_storage: !LogStorage
    output_filename: '/tmp/output_anomalies.log'

  anomalies_storage: !KafkaStorage
    brokers_ips: ['$KAFKA_BROKER_IP:9092']
    topic: wca_anomalies
    max_timeout_in_seconds: 5.

  # Example use of external component.
  # Requires registration with -r example.external_package:ExampleDetector
  detector: !ExampleDetector

  # Decorate every metric with extra labels.
  extra_labels:
    env_id: "$HOST_IP"
