apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -big

resources:
- ../base

commonLabels:
  app: memcached-mutilate-big

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - threads=6
  - load_records=70300000 # 70.3M
  - records=35150000
  - value=1000      # keys 30B + value 1000B = 0.00103 MB * 20M <=  22733 # 80kB * 1.5M  <= 120GB
  - qps=200000

patches:
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: foo
    kind: foo
    metadata:
      name: foo
    spec:
      template:
        spec:
          containers:
          - name: service
            resources:
              requests:
                cpu: 2
                memory: 85G
              limits:
                cpu: 2
                memory: 85G
          - name: generator
            resources:
              requests:
                cpu: 6
                memory: 1G
              limits:
                cpu: 6
                memory: 1G
