apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached-mutilate
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests:
              cpu: 3
              memory: 140G
            limits:
              cpu: 3
              memory: 140G
        - name: mutilate
          resources:
            requests:
              cpu: 4
              memory: 1G
            limits:
              cpu: 4
              memory: 1G
