resources:
  - sysbench-memory.yaml

configMapGenerator:
  - name: sysbench-memory
    literals:
      - threads=4
      - memory=16g
      - report_interval=1
      - extra=

patchesStrategicMerge:
- resources.yaml
- nodeselector.yaml
