loggers:
  wca: DEBUG
  wca.scheduler.server: INFO
  wca.scheduler.algorithms: TRACE
  wca.scheduler.data_providers: DEBUG

kubeapi: &kubeapi !Kubeapi
  host: !Env KUBERNETES_SERVICE_HOST
  port: !Env KUBERNETES_SERVICE_PORT
monitored_namespaces: [ 'default' ]
data_provider: &data_provider !ClusterDataProvider
  kubeapi: *kubeapi
  prometheus: !Prometheus
    # Note: our internal cluster address.
    host: http://prometheus.prometheus.svc.cluster.local
    port: 9090
    timeout: 5.0
  queries: !Queries
    APP_REQUESTED_RESOURCES_QUERY_MAP:
      cpu: 'app_req{dim="cpu"}'
      mem: 'app_req{dim="mem"}'
      wss: 'app_req{dim="wss"}'
    NODE_CAPACITY_RESOURCES_QUERY_MAP:
      wss: 'node_capacity{dim="wss"}'
algorithm: !Fit
  dimensions:
    - mem
    - cpu
    - wss
  data_provider: *data_provider
