apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: wca-scheduler
spec:
  selector:
    matchLabels:
      app: wca-scheduler
  podMetricsEndpoints:
    - path: /metrics
      port: scheduler-http
      interval: 1s
