apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-policy
  namespace: kube-system
data:
  policy.cfg: |
    {
      "AlwaysCheckAllPredicates": true,
      "ExtenderConfigs": [
        {
          "URLPrefix": "https://wca-scheduler-service.wca-scheduler.svc.cluster.local:30180",
          "FilterVerb": "filter",
          "PrioritizeVerb": "prioritize",
          "Weight": 1,
          "EnableHTTPS": true,
          "Ignorable": true,
          "NodeCacheCapable": true
        }
      ]
    }
