apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: specjbb
spec:
  template:
    spec:
      containers:
      # specjbb.controller.preset.ir=30000
        - name: backend
          resources:
            requests:
              cpu: 22
              memory: 60G
            limits:
              cpu: 22
              memory: 60G
        - name: injector
          resources:
            requests:
              cpu: 1
              memory: 3G
            limits:
              cpu: 1
              memory: 3G
        - name: controller
          resources:
            requests:
              cpu: 1
              memory: 3G
            limits:
              cpu: 1
              memory: 3G
