apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- small
- small-wss
- medium
- medium-wss
- big
- big-wss
- _hmem

commonLabels:
  workload: pmbench-normal
  domain: test

images:
- name: pmbench
  newName: 100.64.176.12:80/wca/pmbench
  newTag: master

commonAnnotations:
  topologyhints.cri-resource-manager.intel.com/pod: "false"
