apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: specjbb-group
spec:
  template:
    spec:
      containers:
      # Minimal resource for specjbb.controller.preset.ir=10000
        - name: backend
          resources:
            requests:
              cpu: 5
              memory: 20G
        - name: injector
          resources:
            requests:
              cpu: 1
              memory: 2G
