apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../memcached-mutilate/big
- ../../../redis-memtier/big

commonAnnotations:
  toptierlimit.cri-resource-manager.intel.com/pod: "40G"
