{
 "title": "2LM score dashboard",
 "tags": [ "2lm" ],
 "time": { "from": "now-1m", "to": "now" },
 "panels": [
  {
   "title": "app_req",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_req", "legendFormat": "{{app}} | {{dim}}" }
   ]
  },
  {
   "title": "node_capacity",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 0 },
   "targets": [
    { "expr": "node_capacity", "legendFormat": "{{node}} | {{dim}}" }
   ]
  },
  {
   "title": "profile_nodes_by_cpu{memory=\"2lm\"}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "profile_nodes_by_cpu{memory=\"2lm\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "profile_app_by_cpu_norm",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 19, "w": 9, "x": 0, "y": 19 },
   "targets": [
    { "expr": "profile_app_by_cpu_norm", "legendFormat": "{{app}} | {{index}}" }
   ]
  },
  {
   "title": "profile_nodes_by_cpu{memory=\"1lm\"}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "profile_nodes_by_cpu{memory=\"1lm\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "profile_app_by_cpu_norm",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 19, "w": 4, "x": 9, "y": 24 },
   "targets": [
    { "expr": "profile_app_2lm_score_max", "legendFormat": "{{app}} | SCORE(max)" }
   ]
  },
  {
   "title": "Legend",
   "type": "text",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 24 },
   "content": "\nDefintion | Unit | Equation | Description\n------------ | ---- | ---------| ----\n**mem_density** | `[GB/cpu]`  | `mem` / `cpu` | higher is better \n**mem_intensity (read/write)** | `[GBs/cpu]` | `mbw` / `cpu` | lower is better \n**mem_utilization** | `[GB/cpu]` | `wss` / `cpu` | lower is better\n**SCORE**    | |  `mem_density` - `max`(`mem_intensity`, `mem_utilization`) | higher is better\n\n\n\n\n\n\n\n"
  }
 ]
}