apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: prometheus-rules
  name: prometheus-wca-score
  namespace: prometheus
spec:
  groups:

  - name: score

    # ---- For nodes -----------------------
    # New metrics with following dim=[cpu, mem, wss, mbw_write, mbw_read]
    # end following units: cpu, GB, GB, GBs, GBs
    # node_capacity 
    #   -> profile_node_by_cpu with memory=[1lm, 2lm]
    #       -> profile_nodes_by_cpu_2lm (only for 2LM)
    # 
    #
    # ---- For applications ------------
    # app_count
    # low level:
    #
    # WARNING all level metrics take an average of 10m for tasks
    # app_cpu, app_cpu_usage -> app_cpu_util
    # app_mem, app_mem_usage -> app_mem_util
    # app_req with dim=[cpu, mem, wss, mbw_write, mbw_read]
    # app_mbw, app_mbw_rw, app_mbw_read, app_mbw_write
    #   -> app_req
    #     -> profile_app_by_cpu
    #
    # ---- Profiles -----------------------
    # with index=[mem_density, mem_intesity_read, mem_intesity_write, mem_utilization]
    #  profile_nodes_by_cpu
    #  profile_app_by_cpu
    #    -> profile_app_by_cpu_norm 



    rules:
    # ============================ node ===================================
    # cpu
    - record: node_capacity
      expr: 'sum(platform_topology_cpus) by (node)'
      labels:
        dim: cpu
    # Mem capacity and wss
    # -- wss on 2lm is devaulated to 10% because of direct mapping
    - record: node_capacity
      expr: 'ceil(sum(platform_dimm_total_size_bytes{dimm_type="ram"}) by (node) * 0.1 / 1e9) and on(node) platform_mem_mode_size_bytes!=0'
      labels:
        dim: wss
    # -- ws on 1lm nodes is just capacity of ram
    - record: node_capacity
      expr: 'ceil(sum(platform_dimm_total_size_bytes{dimm_type="ram"}) by (node) / 1e9) and on(node) platform_mem_mode_size_bytes==0'
      labels:
        dim: wss
    - record: node_capacity
      expr: 'ceil(sum(platform_dimm_total_size_bytes{dimm_type="ram"}) by (node) / 1e9) and on(node) platform_mem_mode_size_bytes==0'
      labels:
        dim: mem
    - record: node_capacity
      expr: 'ceil((sum(platform_mem_mode_size_bytes) by (node) / 1e9)) and on(node) platform_mem_mode_size_bytes!=0'
      labels:
        dim: mem
    # BW
    - record: node_capacity
      expr: 'ceil(sum(platform_nvdimm_read_bandwidth_bytes_per_second) by (node) / 1e9) and on(node) platform_mem_mode_size_bytes!=0'
      labels:
        dim: mbw_read
    - record: node_capacity
      expr: 'ceil(sum(platform_dimm_speed_bytes_per_second) by (node) / 1e9) and on(node) platform_mem_mode_size_bytes==0'
      labels:
        dim: mbw_read
    - record: node_capacity
      expr: 'ceil(sum(platform_nvdimm_write_bandwidth_bytes_per_second) by (node) / 1e9) and on(node) platform_mem_mode_size_bytes!=0'
      labels:
        dim: mbw_write
    - record: node_capacity
      expr: 'ceil(sum(platform_dimm_speed_bytes_per_second) by (node) / 1e9) and on(node) platform_mem_mode_size_bytes==0'
      labels:
        dim: mbw_write
    
    # ---------------------------- node nvm profile -----------------------------------------
    # nvm profile only catch pmm nodes!!!!
    # # and on(node) platform_mem_mode_size_bytes!=0

    # Profile by cpu
    - record: profile_node_by_cpu
      expr: 'node_capacity{dim="mem"} / on (node) node_capacity{dim="cpu"}'
      labels:
        index: mem_density
    - record: profile_node_by_cpu
      expr: 'node_capacity{dim="mbw_read"} / on (node) node_capacity{dim="cpu"}'
      labels:
        index: mem_intensity_read
    - record: profile_node_by_cpu
      expr: 'node_capacity{dim="mbw_write"} / on (node) node_capacity{dim="cpu"}'
      labels:
        index: mem_intensity_write
    - record: profile_node_by_cpu
      expr: 'node_capacity{dim="wss"} / on (node) node_capacity{dim="cpu"}'
      labels:
        index: mem_utilization

    # Profile by mem
    - record: profile_node_by_mem
      expr: 'node_capacity{dim="cpu"} / on (node) node_capacity{dim="mem"}'
      labels:
        index: cpu_density
    - record: profile_node_by_mem
      expr: 'node_capacity{dim="mbw_read"} / on (node) node_capacity{dim="mem"}'
      labels:
        index: mem_intensity_read
    - record: profile_node_by_mem
      expr: 'node_capacity{dim="mbw_write"} / on (node) node_capacity{dim="mem"}'
      labels:
        index: mem_intensity_write
    - record: profile_node_by_mem
      expr: 'node_capacity{dim="wss"} / on (node) node_capacity{dim="mem"}'
      labels:
        index: mem_utilization


    # By specific nodes
    # cpu
    - record: profile_nodes_by_cpu
      expr: 'avg(profile_node_by_cpu and on(node) platform_mem_mode_size_bytes==0) by (index)'
      labels:
        memory: 1lm
    - record: profile_nodes_by_cpu
      expr: 'avg(profile_node_by_cpu and on(node) platform_mem_mode_size_bytes!=0) by (index)'
      labels:
        memory: 2lm
    # mem
    - record: profile_nodes_by_mem
      expr: 'avg(profile_node_by_mem and on(node) platform_mem_mode_size_bytes==0) by (index)'
      labels:
        memory: 1lm
    - record: profile_nodes_by_mem
      expr: 'avg(profile_node_by_mem and on(node) platform_mem_mode_size_bytes!=0) by (index)'
      labels:
        memory: 2lm

    # ============================ apps ===================================
    - record: app_count
      expr: count(task_up) by (app)

    # very low metric
    - record: task_memory_rw_ratio
      expr: rate(task_offcore_requests_demand_data_rd[10m]) / (rate(task_offcore_requests_demand_data_rd[10m]) + rate(task_offcore_requests_demand_rfo[10m]))

    # ---- low level metrics for apps [10m]
    - record: app_cpu
      expr: avg(max_over_time(task_requested_cpus[10m])) by (app)
    - record: app_cpu_usage
      expr: ceil(avg(rate(task_cpu_usage_seconds[10m])) by (app))
    - record: app_cpu_util
      expr: app_cpu_usage/app_cpu

    - record: app_mem
      expr: avg(max_over_time(task_requested_mem_bytes[10m])) by (app) / 1e9
    - record: app_mem_usage
      expr: avg(avg_over_time(task_mem_usage_bytes[10m])) by(app) / 1e9
    - record: app_mem_util
      expr: app_mem_usage/app_mem

    # ---- mem bandwidth [gb/s]
    - record: app_mbw
      expr: max(irate(task_mem_bandwidth_bytes[10m])) by (app) / 1e9
    # ---- r/w and read/write bandwidth
    - record: app_mbw_rw
      expr: avg(task_memory_rw_ratio) by (app)
    - record: app_mbw_read
      expr: ceil(app_mbw * app_mbw_rw)
    - record: app_mbw_write
      expr: ceil(app_mbw * (1-app_mbw_rw))
    # --- wss [gb]
    - record: app_wss   # gb collected over 15s
      expr: ceil((avg(avg_over_time(task_wss_referenced_bytes[10m])) by (app)) / 1e9)

    # just a mapping app_req to use labels: cpu, mem, mbw_read, mbw_write, wss
    - record: app_req
      expr: app_cpu
      labels:
        dim: cpu
    - record: app_req
      expr: app_mem
      labels:
        dim: mem
    - record: app_req
      expr: app_mbw_read
      labels:
        dim: mbw_read
    - record: app_req
      expr: app_mbw_write
      labels:
        dim: mbw_write
    - record: app_req
      expr: app_wss
      labels:
        dim: wss


    # --------------------- Profiles APP -----------------------

    # app profile by cpu
    - record: profile_app_by_cpu
      expr: app_req{dim="mem"} / on(app) app_req{dim="cpu"}
      labels:
        index: mem_density
    - record: profile_app_by_cpu
      expr: app_req{dim="mbw_read"} / on(app) app_req{dim="cpu"}
      labels:
        index: mem_intensity_read
    - record: profile_app_by_cpu
      expr: app_req{dim="mbw_write"} / on(app) app_req{dim="cpu"}
      labels:
        index: mem_intensity_write
    - record: profile_app_by_cpu
      expr: app_req{dim="wss"} / on(app) app_req{dim="cpu"}
      labels:
        index: mem_utilization

    # app profile by mem
    - record: profile_app_by_mem
      expr: app_req{dim="cpu"} / on(app) app_req{dim="mem"}
      labels:
        index: cpu_density
    - record: profile_app_by_mem
      expr: app_req{dim="mbw_read"} / on(app) app_req{dim="mem"}
      labels:
        index: mem_intensity_read
    - record: profile_app_by_mem
      expr: app_req{dim="mbw_write"} / on(app) app_req{dim="mem"}
      labels:
        index: mem_intensity_write
    - record: profile_app_by_mem
      expr: app_req{dim="wss"} / on(app) app_req{dim="mem"}
      labels:
        index: mem_utilization


    # ======================== normalization profile ========================
    - record: profile_app_by_cpu_norm
      expr: profile_app_by_cpu / on(index) group_left profile_nodes_by_cpu{memory="2lm"}
    - record: profile_app_by_mem_norm
      expr: profile_app_by_mem / on (index) group_left profile_nodes_by_mem{memory="2lm"}

    # ======================== SCORE calculation ==========================
    - record: profile_app_2lm_score_positive # higher is better for 2lm
      expr: profile_app_by_cpu_norm{index="mem_density"}

    - record: profile_app_2lm_score_negative_sum # lower is better for 2lm
      expr: sum(profile_app_by_cpu_norm{index=~"mem_intensity_read|mem_intensity_write|mem_utilization"}) by (app)

    - record: profile_app_2lm_score_negative_max # lower is better for 2lm
      expr: max(profile_app_by_cpu_norm{index=~"mem_intensity_read|mem_intensity_write|mem_utilization"}) by (app)

    - record: profile_app_2lm_score_max # higher is better for 2lm
      expr: profile_app_2lm_score_positive - on(app) group_left() profile_app_2lm_score_negative_max
    - record: profile_app_2lm_score_sum # higher is better for 2lm
      expr: profile_app_2lm_score_positive - on(app) group_left() profile_app_2lm_score_negative_sum

    - record: drozdzan_test # higher is better for 2lm
      expr: profile_app_by_cpu

    # ======================== SCORE2 calculation ==========================
    - record: profile_app_2lm_score2_positive # higher is better for 2lm
      expr: profile_app_by_mem_norm{index="cpu_density"}

    - record: profile_app_2lm_score2_negative_sum # lower is better for 2lm
      expr: sum(profile_app_by_mem_norm{index=~"mem_intensity_read|mem_intensity_write|mem_utilization"}) by (app)

    - record: profile_app_2lm_score2_negative_max # lower is better for 2lm
      expr: max(profile_app_by_mem_norm{index=~"mem_intensity_read|mem_intensity_write|mem_utilization"}) by (app)

    - record: profile_app_2lm_score2_max # higher is better for 2lm
      expr: profile_app_2lm_score2_positive - on(app) group_left() profile_app_2lm_score2_negative_max
    - record: profile_app_2lm_score2_sum # higher is better for 2lm
      expr: profile_app_2lm_score2_positive - on(app) group_left() profile_app_2lm_score2_negative_sum

    - record: drozdzan_test # higher is better for 2lm
      expr: profile_app_by_mem

  - name: cluster-score-data-provider
    rules:
      - record: node_type
        expr: 'platform_mem_mode_size_bytes > 0'
        labels:
          nodetype: pmem

      - record: node_type
        expr: 'platform_mem_mode_size_bytes == 0'
        labels:
          nodetype: dram

      - record: node_type
        expr: 'platform_mem_mode_size_bytes < 0'
        labels:
          nodetype: unknown
      
      - record: app_profile
        expr: 'profile_app_2lm_score_max'
