apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook
  name: webhook
  namespace: webhook
spec:
  ports:
  - name: https
    port: 443
    targetPort: 5000
  selector:
    app: webhook
  sessionAffinity: None
  type: ClusterIP

