tests:
  - test_case_name1:	
    tasks: 
      - /buu/buu/task1										# -> cgroup_path=/task1 
      - /be/ble/task2  							# -> cgroup_path=/be/ble/task2 name=task2 task_id=task2 -> Task
    allocations_rules: # Rules
      - name: wszycy maja jedna quaota
        allocations:
          cpu_quota: 1
      - name: task z lableka be mam miec RDT cache=1m
        labels:
          name: be
        allocations:
          rdt:
            cache: 1
    checks:

  - test_case_name2:	
    tasks: 
      - /buu/buu/task1										# -> cgroup_path=/task1 
      - /be/ble/task2  							# -> cgroup_path=/be/ble/task2 name=task2 task_id=task2 -> Task
    allocations_rules: # Rules
      - name: wszycy maja jedna quaota
        allocations:
          cpu_quota: 1
      - name: task z lableka be mam miec RDT cache=1m
        labels:
          name: be
        allocations:
          rdt:
            cache: 1
    checks:
      - !FileCheck
        path: /tmp/owca/dupa
        value: '250'
        subvalue: '25'
      - !MetricCheck

