apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -medium

resources:
- ../base

commonLabels:
  app: pmbench-normal-medium

configMapGenerator:
- name: pmbench-normal
  behavior: merge
  literals:
    - extra='--pattern normal --shape 640000 --setsize 40000 --mapsize 40000 2000000 --initialize -a touch -j 4'

  # for 20GB wss, you should use --shape 640000
  # 1sigma(68%) offset= 2500MiB  640000pages   accessed memory= 5000MiB  1280000pages
  # 2sigma(95%) offset= 5000MiB 1280000pages   accessed memory=10000MiB  2560000pages
  # 3sigma(99%) offset=10000MiB 2560000pages   accessed memory=20000MiB  5120000pages

patches:
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: foo
    kind: foo
    metadata:
      name: foo
    spec:
      template:
        spec:
          containers:
          - name: generator
            resources:
              requests:
                cpu: 8
                memory: 45G
              limits:
                cpu: 8
                memory: 45G
