runner: !MeasurementRunner
  interval: 1.0
  node: !StaticNode
    tasks: []
    # Will look for tasks(dynamic cgroups) in /sys/fs/cgroup/cpu/docker/[task_ids]
    directory: docker
  metrics_storage: !LogStorage
    output_filename: metrics.prom
    overwrite: true
