runner: !AllocationRunner
  node: &tester !Tester
   config: 'example/tester_config.yaml'
  action_delay: 5.
  metrics_storage: *tester
  anomalies_storage: *tester
  allocations_storage: *tester
  allocator: *tester
  rdt_enabled: false
