apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -small

resources:
- ../base

commonLabels:
  app: memcached-mutilate-small

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - threads=8
  - load_records=17575000 # 70.3M   # 1.5M
  - records=8787500
  - value=1000      # keys 30B + value 1000B = 0.00103 MB * 20M <=  22733 # 80kB * 1.5M  <= 120GB
  - qps=300000        # 13k

patches:
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: foo
    kind: foo
    metadata:
      name: foo
    spec:
      template:
        spec:
          containers:
          - name: service
            resources:
              requests:
                cpu: 2
                memory: 22G
              limits:
                cpu: 2
                memory: 22G
          - name: generator
            resources:
              requests:
                cpu: 6
                memory: 1G
              limits:
                cpu: 6
                memory: 1G