apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wca

images:
  - name: wca
    newName: 100.64.176.12:80/wca
    newTag: master

resources:
  - daemonset.yaml
  - service.yaml
  - service_account.yaml
  - service_monitor.yaml
  - priority_class.yaml

configMapGenerator:
  - name: wca-config
    files:
    - wca-config.yaml
