nameSuffix: -dram-pmem

resources:
- ../../small
- ../../small-wss
- ../../medium
- ../../medium-wss
- ../../big
- ../../big-wss


commonAnnotations:
  cri-resource-manager.intel.com/memory-type: |
    service: dram,pmem
    generator: dram,pmem
