apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  clusterIP: None
  selector:
    app: memcached

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached
spec:
  replicas: 0
  serviceName: memcached
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        goal: service
      containers:
        - name: memcached
          image: memcached
          envFrom:
            - configMapRef:
                name: memcached
          command:
            - sh
            - -c
            - >
              memcached
              -t $threads
              -m $memory
              -u root
              $extra

  # required for workaround bug with kustomize https://github.com/kubernetes-sigs/kustomize/issues/504
  # when using commonLabels
  # fixed in 2.1.0 https://github.com/kubernetes-sigs/kustomize/commit/c470982ce5b96da82a757f088a842bb05d3bcdb4
  volumeClaimTemplates: []
