runner: !AllocationRunner
  node: !Tester
   config: 'example/tester_config.yaml'
  action_delay: 5.
  metrics_storage: !LogStorage
    output_filename: metrics.logs
  anomalies_storage: !LogStorage
    output_filename: anomalies.logs
  allocations_storage: !LogStorage
    output_filename: allocations.logs
  allocator: !Tester
    config: 'example/tester_config.yaml'
  rdt_enabled: false
