apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: webhook.webhook
spec:
  groups:
  - system:authenticated
  request: ${REQUEST}
  usages:
  - digital signature
  - key encipherment
  - server auth
