apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: specjbb-group
spec:
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 5
              memory: 7.5G # Must be equation: 1.5*cpu = memory
