apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pmbench
spec:
  template:
    spec:
      containers:
        - name: pmbench
          resources:
            requests:
              cpu: 9
              memory: 100G
            limits:
              cpu: 9
              memory: 100G
