apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -big-wss

resources:
- ../base

commonLabels:
  app: memcached-mutilate-big-wss

configMapGenerator:
- name: mutilate
  behavior: merge
  literals:
  - threads=8
  - load_records=20000000 # 20M   # 1.5M
  - records=10000000
  - value=1000      # 1kB * 20M <=  # 80kB * 1.5M  <= 120GB
  - qps=13000        # 13k

patches:
- target:
    kind: StatefulSet
  patch: |-
    apiVersion: foo
    kind: foo
    metadata:
      name: foo
    spec:
      template:
        spec:
          containers:
          - name: service
            resources:
              requests:
                cpu: 8
                memory: 85G
              limits:
                cpu: 8
                memory: 85G
          - name: generator
            resources:
              requests:
                cpu: 8
                memory: 1G
              limits:
                cpu: 8
                memory: 1G
